"""Pydantic v2 request/response models — the public contract of the API."""

from datetime import datetime
from typing import TypedDict
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from models.message import Role


# ==========================================
# FASTAPI API CONTRACTS
# ==========================================
class ConversationCreate(BaseModel):
    title: str = Field(min_length=1, max_length=200, examples=["FastAPI doubts"])
    owner_id: str = Field(min_length=1, max_length=64, examples=["student_01"])


class ConversationOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    title: str
    owner_id: str
    is_archived: bool
    created_at: datetime
    updated_at: datetime


class MessageOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    role: Role
    content: str
    model: str | None = None
    input_tokens: int | None = None
    output_tokens: int | None = None
    latency_ms: int | None = None
    created_at: datetime


class ChatRequest(BaseModel):
    message: str = Field(min_length=1, max_length=8000, examples=["Explain dependency injection."])


class ChatResponse(BaseModel):
    conversation_id: UUID
    reply: str
    model: str
    latency_ms: int
    history_length: int


# ==========================================
# LANGGRAPH STATE
# ==========================================
class LoanState(TypedDict):
    gender: str | None
    age: int | None
    marital_status: str | None
    employment_status: str | None
    has_child: bool | None

    # Outputs generated by the graph
    loan_amount: int | None
    interest_rate: int | None
    bot_message: str | None
